# Generated by Django 5.2.5 on 2025-12-02 22:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='reviews/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'webm'])], verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='review.review')),
            ],
            options={
                'verbose_name': 'Media đánh giá',
                'verbose_name_plural': 'Media đánh giá',
            },
        ),
    ]
